<#	
	.NOTES
	===========================================================================
	 Created with: 	SAPIEN Technologies, Inc., PowerShell Studio 2017 v5.4.145
	 Created on:   	12/19/2017 17:01
	 Created by:   	NWendlowsky
	 Organization: 	Paylocity
	 Filename:     	
	===========================================================================
	.DESCRIPTION
		Updates several 3rd party applications by scraping sites for latest versions,
		downloading content, placing content into structured folders, creating new source folders for SCCM,
		updating variables within those scripts, and auto-creating and deploying new apps in SCCM AppStore.
#>

#region Define Variables

[string]$SiteServer = 'AH-SCCM-01'
[string]$Date = Get-Date -Format yyyy-M-d-HH:mm:ss
[string]$SiteCode = 'PAY'
[string]$DomainName = 'Paylocity'
[string]$TLDomain = 'com'
[string]$Domain = $DomainName + '.' + $TLDomain
[string]$SiteFQDN = $SiteServer + '.' + $Domain
[string]$SoftwareContent = '\\kirk\it\software'
[string]$CSVPath = 'c:\Tools\ApplicationUpdates'
[string]$CSVName = 'AppList.csv'
[string]$CSVFullName = $CSVPath + '\' + $CSVName
[string]$appOwner = '_EUCEngineers'
[string]$AdminCommnet = "This was auto-generated by ApplicationUpdates.ps1 script on $Date"


$AppList = Import-Csv -Path $CSVFullName -Delimiter ','
$AppCount = $AppList | Measure-Object
$AppCount.Count

$AppList | ForEach-Object{
	
	if (!([string]::IsNullOrEmpty($_.AppPublisher)) -and !([string]::IsNullOrEmpty($_.Appname)) -and !([string]::IsNullOrEmpty($_.AppVersion)) -and !([string]::IsNullOrEmpty($_.AppDescription)) -and !([string]::IsNullOrEmpty($_.IconName))) {
		#Try{
		$AppAdminName = $_.AppName + ' ' + $_.AppVersion
		$CreatedApplication = New-CMApplication -Name "$AppAdminName test" -IconLocationFile "$($CSVPath)\$($_.IconName)" -AutoInstall $true -IsFeatured $False -LocalizedDescription "$($_.AppDescription)" -LocalizedName "$($_.AppName)" -Owner "$AppOwner" -Publisher "$($_.AppPublisher)" -SoftwareVersion "$($_.AppVersion)"
		$CreatedDeploymentType = Add-CMDeploymentType -DeploymentTypeName "$($_.AppName)_$($_.AppVersion)" -InstallationProgram "Install.bat" -AdministratorComment "$AdminComment" -ContentLocation "$SoftwareContent\$_.AppPublisher\$_.AppName\$_.AppVersion" -EstimatedInstallationTimeMins 15 -InstallationBehaviorType InstallForSystem -InstallationProgramVisibility Normal -LogonRequirementType WhetherOrNotUserLoggedOn -MaximumAllowedRunTimeMins 120 -OnSlowNetworkMode Download -UninstallProgram "Uninstall.bat"
		Switch ($_.AppDetectionClause) {
			WindowsInstaller{
				New-CMDetectionClauseWindowsInstaller -ExpectedValue ("$($_.AppVersion)") -ExpressionOperator IsEquals -ProductCode ("$($_.ProductCode)") -Value -PropertyType ProductVersion
			}
			RegistryKey{
				New-CMDetectionClauseRegistryKey -Hive "$($_.AppRegHive)" -KeyName "$($_.AppRegKeyPath)" -Existence
			}
			RegistryKeyValue{
			}
			File{
			}
		}
		$CreatedDetectionMethod =
		
		
		#$AppCreated | Get-ItemProperty
		#}catch{
		#Write-Host "Creation failed."
		#break
		#}
	} else {
		Write-Host "Error! Value in CSV on Line $LineNumber is empty, exiting."
	}
}