select
CI_ID
,ApplicabilityCondition
,CI_CRC
,CI_UniqueID
,CIInformativeURL
,CIType_ID
,CIVersion
,ConfigurationFlags
,ContentSourcePath
,CreatedBy
,DateCreated
,DateLastModified
,Description
,DisplayName
,EffectiveDate
,Featured
,HasContent
,InUse
,IsBroken
,IsChild
,IsDeployable
,IsDeployed
,IsEnabled
,IsExpired
,IsHidden
,IsLatest
,IsQuarantined
,IsSignificantRevision
,IsSuperseded
,IsSuperseding
,IsTombstoned
,IsUserCI
,IsUserDefined
,LastModifiedBy
,LocaleID
,LogonRequirement
,Manufacturer
,ModelID
,ModelName
,ModifiedTime
,NumberOfDependedDTs
,NumberOfDependentTS
,NumberOfDeployments
,NumberOfDeploymentTypes
,NumberOfDevicesWithApp
,NumberOfDevicesWithFailure
,NumberOfSettings
,NumberOfUsersWithApp
,NumberOfUsersWithFailure
,NumberOfUsersWithRequest
,NumberOfVirtualEnvironments
,PlatformType
,RevisionTag
,SedoObjectVersion
,SoftwareVersion
,SourceCIVersion
,SourceModelName
,SourceSite
,SummarizationTime

from fn_ListLatestApplicationCIs(1033)